name: Flake8 Pull Request Check

on:
  pull_request:
    branches:
      - main 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Validate code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
    - name: Install dependencies and Run test script
      run: |
        uv build
        flake8 test/run_test.py